# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WAMessage.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class UserAgentUserAgentPlatform(betterproto.Enum):
    ANDROID = 0
    IOS = 1
    WINDOWS_PHONE = 2
    BLACKBERRY = 3
    BLACKBERRYX = 4
    S40 = 5
    S60 = 6
    PYTHON_CLIENT = 7
    TIZEN = 8
    ENTERPRISE = 9
    SMB_ANDROID = 10
    KAIOS = 11
    SMB_IOS = 12
    WINDOWS = 13
    WEB = 14
    PORTAL = 15
    GREEN_ANDROID = 16
    GREEN_IPHONE = 17
    BLUE_ANDROID = 18
    BLUE_IPHONE = 19
    FBLITE_ANDROID = 20
    MLITE_ANDROID = 21
    IGLITE_ANDROID = 22
    PAGE = 23
    MACOS = 24
    VR = 25


class UserAgentUserAgentReleaseChannel(betterproto.Enum):
    RELEASE = 0
    BETA = 1
    ALPHA = 2
    DEBUG = 3


class WebInfoWebInfoWebSubPlatform(betterproto.Enum):
    WEB_BROWSER = 0
    APP_STORE = 1
    WIN_STORE = 2
    DARWIN = 3
    WIN32 = 4


class DNSSourceDNSSourceDNSResolutionMethod(betterproto.Enum):
    SYSTEM = 0
    GOOGLE = 1
    HARDCODED = 2
    OVERRIDE = 3
    FALLBACK = 4


class ClientPayloadClientPayloadClientFeature(betterproto.Enum):
    NONE = 0


class ClientPayloadClientPayloadIOSAppExtension(betterproto.Enum):
    SHARE_EXTENSION = 0
    SERVICE_EXTENSION = 1
    INTENTS_EXTENSION = 2


class ClientPayloadClientPayloadConnectType(betterproto.Enum):
    CELLULAR_UNKNOWN = 0
    WIFI_UNKNOWN = 1
    CELLULAR_EDGE = 100
    CELLULAR_IDEN = 101
    CELLULAR_UMTS = 102
    CELLULAR_EVDO = 103
    CELLULAR_GPRS = 104
    CELLULAR_HSDPA = 105
    CELLULAR_HSUPA = 106
    CELLULAR_HSPA = 107
    CELLULAR_CDMA = 108
    CELLULAR_1XRTT = 109
    CELLULAR_EHRPD = 110
    CELLULAR_LTE = 111
    CELLULAR_HSPAP = 112


class ClientPayloadClientPayloadConnectReason(betterproto.Enum):
    PUSH = 0
    USER_ACTIVATED = 1
    SCHEDULED = 2
    ERROR_RECONNECT = 3
    NETWORK_SWITCH = 4
    PING_RECONNECT = 5


class ClientPayloadClientPayloadProduct(betterproto.Enum):
    WHATSAPP = 0
    MESSENGER = 1


class BizIdentityInfoBizIdentityInfoVerifiedLevelValue(betterproto.Enum):
    UNKNOWN = 0
    LOW = 1
    HIGH = 2


class BizIdentityInfoBizIdentityInfoHostStorageType(betterproto.Enum):
    ON_PREMISE = 0
    FACEBOOK = 1


class BizIdentityInfoBizIdentityInfoActualActorsType(betterproto.Enum):
    SELF = 0
    BSP = 1


class BizAccountLinkInfoBizAccountLinkInfoHostStorageType(betterproto.Enum):
    ON_PREMISE = 0
    FACEBOOK = 1


class BizAccountLinkInfoBizAccountLinkInfoAccountType(betterproto.Enum):
    ENTERPRISE = 0
    PAGE = 1


class SyncdMutationSyncdMutationSyncdOperation(betterproto.Enum):
    SET = 0
    REMOVE = 1


class MediaRetryNotificationMediaRetryNotificationResultType(betterproto.Enum):
    GENERAL_ERROR = 0
    SUCCESS = 1
    NOT_FOUND = 2
    DECRYPTION_ERROR = 3


class ConversationConversationEndOfHistoryTransferType(betterproto.Enum):
    COMPLETE_BUT_MORE_MESSAGES_REMAIN_ON_PRIMARY = 0
    COMPLETE_AND_NO_MORE_MESSAGE_REMAIN_ON_PRIMARY = 1


class HistorySyncHistorySyncHistorySyncType(betterproto.Enum):
    INITIAL_BOOTSTRAP = 0
    INITIAL_STATUS_V3 = 1
    FULL = 2
    RECENT = 3
    PUSH_NAME = 4


class AdReplyInfoAdReplyInfoMediaType(betterproto.Enum):
    NONE = 0
    IMAGE = 1
    VIDEO = 2


class ExternalAdReplyInfoExternalAdReplyInfoMediaType(betterproto.Enum):
    NONE = 0
    IMAGE = 1
    VIDEO = 2


class InvoiceMessageInvoiceMessageAttachmentType(betterproto.Enum):
    IMAGE = 0
    PDF = 1


class ExtendedTextMessageExtendedTextMessageFontType(betterproto.Enum):
    SANS_SERIF = 0
    SERIF = 1
    NORICAN_REGULAR = 2
    BRYNDAN_WRITE = 3
    BEBASNEUE_REGULAR = 4
    OSWALD_HEAVY = 5


class ExtendedTextMessageExtendedTextMessagePreviewType(betterproto.Enum):
    NONE = 0
    VIDEO = 1


class VideoMessageVideoMessageAttribution(betterproto.Enum):
    NONE = 0
    GIPHY = 1
    TENOR = 2


class ProtocolMessageProtocolMessageType(betterproto.Enum):
    REVOKE = 0
    EPHEMERAL_SETTING = 3
    EPHEMERAL_SYNC_RESPONSE = 4
    HISTORY_SYNC_NOTIFICATION = 5
    APP_STATE_SYNC_KEY_SHARE = 6
    APP_STATE_SYNC_KEY_REQUEST = 7
    MSG_FANOUT_BACKFILL_REQUEST = 8
    INITIAL_SECURITY_NOTIFICATION_SETTING_SYNC = 9
    APP_STATE_FATAL_EXCEPTION_NOTIFICATION = 10


class HistorySyncNotificationHistorySyncNotificationHistorySyncType(betterproto.Enum):
    INITIAL_BOOTSTRAP = 0
    INITIAL_STATUS_V3 = 1
    FULL = 2
    RECENT = 3
    PUSH_NAME = 4


class HSMDateTimeComponentHSMDateTimeComponentDayOfWeekType(betterproto.Enum):
    MONDAY = 1
    TUESDAY = 2
    WEDNESDAY = 3
    THURSDAY = 4
    FRIDAY = 5
    SATURDAY = 6
    SUNDAY = 7


class HSMDateTimeComponentHSMDateTimeComponentCalendarType(betterproto.Enum):
    GREGORIAN = 1
    SOLAR_HIJRI = 2


class PaymentInviteMessagePaymentInviteMessageServiceType(betterproto.Enum):
    UNKNOWN = 0
    FBPAY = 1
    NOVI = 2
    UPI = 3


class OrderMessageOrderMessageOrderStatus(betterproto.Enum):
    INQUIRY = 1


class OrderMessageOrderMessageOrderSurface(betterproto.Enum):
    CATALOG = 1


class ListMessageListMessageListType(betterproto.Enum):
    UNKNOWN = 0
    SINGLE_SELECT = 1
    PRODUCT_LIST = 2


class ListResponseMessageListResponseMessageListType(betterproto.Enum):
    UNKNOWN = 0
    SINGLE_SELECT = 1


class ButtonButtonType(betterproto.Enum):
    UNKNOWN = 0
    RESPONSE = 1
    NATIVE_FLOW = 2


class ButtonsMessageButtonsMessageHeaderType(betterproto.Enum):
    UNKNOWN = 0
    EMPTY = 1
    TEXT = 2
    DOCUMENT = 3
    IMAGE = 4
    VIDEO = 5
    LOCATION = 6


class ButtonsResponseMessageButtonsResponseMessageType(betterproto.Enum):
    UNKNOWN = 0
    DISPLAY_TEXT = 1


class CompanionPropsCompanionPropsPlatformType(betterproto.Enum):
    UNKNOWN = 0
    CHROME = 1
    FIREFOX = 2
    IE = 3
    OPERA = 4
    SAFARI = 5
    EDGE = 6
    DESKTOP = 7
    IPAD = 8
    ANDROID_TABLET = 9
    OHANA = 10
    ALOHA = 11
    CATALINA = 12


class WebFeaturesWebFeaturesFlag(betterproto.Enum):
    NOT_STARTED = 0
    FORCE_UPGRADE = 1
    DEVELOPMENT = 2
    PRODUCTION = 3


class PaymentInfoPaymentInfoCurrency(betterproto.Enum):
    UNKNOWN_CURRENCY = 0
    INR = 1


class PaymentInfoPaymentInfoStatus(betterproto.Enum):
    UNKNOWN_STATUS = 0
    PROCESSING = 1
    SENT = 2
    NEED_TO_ACCEPT = 3
    COMPLETE = 4
    COULD_NOT_COMPLETE = 5
    REFUNDED = 6
    EXPIRED = 7
    REJECTED = 8
    CANCELLED = 9
    WAITING_FOR_PAYER = 10
    WAITING = 11


class PaymentInfoPaymentInfoTxnStatus(betterproto.Enum):
    UNKNOWN = 0
    PENDING_SETUP = 1
    PENDING_RECEIVER_SETUP = 2
    INIT = 3
    SUCCESS = 4
    COMPLETED = 5
    FAILED = 6
    FAILED_RISK = 7
    FAILED_PROCESSING = 8
    FAILED_RECEIVER_PROCESSING = 9
    FAILED_DA = 10
    FAILED_DA_FINAL = 11
    REFUNDED_TXN = 12
    REFUND_FAILED = 13
    REFUND_FAILED_PROCESSING = 14
    REFUND_FAILED_DA = 15
    EXPIRED_TXN = 16
    AUTH_CANCELED = 17
    AUTH_CANCEL_FAILED_PROCESSING = 18
    AUTH_CANCEL_FAILED = 19
    COLLECT_INIT = 20
    COLLECT_SUCCESS = 21
    COLLECT_FAILED = 22
    COLLECT_FAILED_RISK = 23
    COLLECT_REJECTED = 24
    COLLECT_EXPIRED = 25
    COLLECT_CANCELED = 26
    COLLECT_CANCELLING = 27
    IN_REVIEW = 28


class WebMessageInfoWebMessageInfoStatus(betterproto.Enum):
    ERROR = 0
    PENDING = 1
    SERVER_ACK = 2
    DELIVERY_ACK = 3
    READ = 4
    PLAYED = 5


class WebMessageInfoWebMessageInfoStubType(betterproto.Enum):
    UNKNOWN = 0
    REVOKE = 1
    CIPHERTEXT = 2
    FUTUREPROOF = 3
    NON_VERIFIED_TRANSITION = 4
    UNVERIFIED_TRANSITION = 5
    VERIFIED_TRANSITION = 6
    VERIFIED_LOW_UNKNOWN = 7
    VERIFIED_HIGH = 8
    VERIFIED_INITIAL_UNKNOWN = 9
    VERIFIED_INITIAL_LOW = 10
    VERIFIED_INITIAL_HIGH = 11
    VERIFIED_TRANSITION_ANY_TO_NONE = 12
    VERIFIED_TRANSITION_ANY_TO_HIGH = 13
    VERIFIED_TRANSITION_HIGH_TO_LOW = 14
    VERIFIED_TRANSITION_HIGH_TO_UNKNOWN = 15
    VERIFIED_TRANSITION_UNKNOWN_TO_LOW = 16
    VERIFIED_TRANSITION_LOW_TO_UNKNOWN = 17
    VERIFIED_TRANSITION_NONE_TO_LOW = 18
    VERIFIED_TRANSITION_NONE_TO_UNKNOWN = 19
    GROUP_CREATE = 20
    GROUP_CHANGE_SUBJECT = 21
    GROUP_CHANGE_ICON = 22
    GROUP_CHANGE_INVITE_LINK = 23
    GROUP_CHANGE_DESCRIPTION = 24
    GROUP_CHANGE_RESTRICT = 25
    GROUP_CHANGE_ANNOUNCE = 26
    GROUP_PARTICIPANT_ADD = 27
    GROUP_PARTICIPANT_REMOVE = 28
    GROUP_PARTICIPANT_PROMOTE = 29
    GROUP_PARTICIPANT_DEMOTE = 30
    GROUP_PARTICIPANT_INVITE = 31
    GROUP_PARTICIPANT_LEAVE = 32
    GROUP_PARTICIPANT_CHANGE_NUMBER = 33
    BROADCAST_CREATE = 34
    BROADCAST_ADD = 35
    BROADCAST_REMOVE = 36
    GENERIC_NOTIFICATION = 37
    E2E_IDENTITY_CHANGED = 38
    E2E_ENCRYPTED = 39
    CALL_MISSED_VOICE = 40
    CALL_MISSED_VIDEO = 41
    INDIVIDUAL_CHANGE_NUMBER = 42
    GROUP_DELETE = 43
    GROUP_ANNOUNCE_MODE_MESSAGE_BOUNCE = 44
    CALL_MISSED_GROUP_VOICE = 45
    CALL_MISSED_GROUP_VIDEO = 46
    PAYMENT_CIPHERTEXT = 47
    PAYMENT_FUTUREPROOF = 48
    PAYMENT_TRANSACTION_STATUS_UPDATE_FAILED = 49
    PAYMENT_TRANSACTION_STATUS_UPDATE_REFUNDED = 50
    PAYMENT_TRANSACTION_STATUS_UPDATE_REFUND_FAILED = 51
    PAYMENT_TRANSACTION_STATUS_RECEIVER_PENDING_SETUP = 52
    PAYMENT_TRANSACTION_STATUS_RECEIVER_SUCCESS_AFTER_HICCUP = 53
    PAYMENT_ACTION_ACCOUNT_SETUP_REMINDER = 54
    PAYMENT_ACTION_SEND_PAYMENT_REMINDER = 55
    PAYMENT_ACTION_SEND_PAYMENT_INVITATION = 56
    PAYMENT_ACTION_REQUEST_DECLINED = 57
    PAYMENT_ACTION_REQUEST_EXPIRED = 58
    PAYMENT_ACTION_REQUEST_CANCELLED = 59
    BIZ_VERIFIED_TRANSITION_TOP_TO_BOTTOM = 60
    BIZ_VERIFIED_TRANSITION_BOTTOM_TO_TOP = 61
    BIZ_INTRO_TOP = 62
    BIZ_INTRO_BOTTOM = 63
    BIZ_NAME_CHANGE = 64
    BIZ_MOVE_TO_CONSUMER_APP = 65
    BIZ_TWO_TIER_MIGRATION_TOP = 66
    BIZ_TWO_TIER_MIGRATION_BOTTOM = 67
    OVERSIZED = 68
    GROUP_CHANGE_NO_FREQUENTLY_FORWARDED = 69
    GROUP_V4_ADD_INVITE_SENT = 70
    GROUP_PARTICIPANT_ADD_REQUEST_JOIN = 71
    CHANGE_EPHEMERAL_SETTING = 72
    E2E_DEVICE_CHANGED = 73
    VIEWED_ONCE = 74
    E2E_ENCRYPTED_NOW = 75
    BLUE_MSG_BSP_FB_TO_BSP_PREMISE = 76
    BLUE_MSG_BSP_FB_TO_SELF_FB = 77
    BLUE_MSG_BSP_FB_TO_SELF_PREMISE = 78
    BLUE_MSG_BSP_FB_UNVERIFIED = 79
    BLUE_MSG_BSP_FB_UNVERIFIED_TO_SELF_PREMISE_VERIFIED = 80
    BLUE_MSG_BSP_FB_VERIFIED = 81
    BLUE_MSG_BSP_FB_VERIFIED_TO_SELF_PREMISE_UNVERIFIED = 82
    BLUE_MSG_BSP_PREMISE_TO_SELF_PREMISE = 83
    BLUE_MSG_BSP_PREMISE_UNVERIFIED = 84
    BLUE_MSG_BSP_PREMISE_UNVERIFIED_TO_SELF_PREMISE_VERIFIED = 85
    BLUE_MSG_BSP_PREMISE_VERIFIED = 86
    BLUE_MSG_BSP_PREMISE_VERIFIED_TO_SELF_PREMISE_UNVERIFIED = 87
    BLUE_MSG_CONSUMER_TO_BSP_FB_UNVERIFIED = 88
    BLUE_MSG_CONSUMER_TO_BSP_PREMISE_UNVERIFIED = 89
    BLUE_MSG_CONSUMER_TO_SELF_FB_UNVERIFIED = 90
    BLUE_MSG_CONSUMER_TO_SELF_PREMISE_UNVERIFIED = 91
    BLUE_MSG_SELF_FB_TO_BSP_PREMISE = 92
    BLUE_MSG_SELF_FB_TO_SELF_PREMISE = 93
    BLUE_MSG_SELF_FB_UNVERIFIED = 94
    BLUE_MSG_SELF_FB_UNVERIFIED_TO_SELF_PREMISE_VERIFIED = 95
    BLUE_MSG_SELF_FB_VERIFIED = 96
    BLUE_MSG_SELF_FB_VERIFIED_TO_SELF_PREMISE_UNVERIFIED = 97
    BLUE_MSG_SELF_PREMISE_TO_BSP_PREMISE = 98
    BLUE_MSG_SELF_PREMISE_UNVERIFIED = 99
    BLUE_MSG_SELF_PREMISE_VERIFIED = 100
    BLUE_MSG_TO_BSP_FB = 101
    BLUE_MSG_TO_CONSUMER = 102
    BLUE_MSG_TO_SELF_FB = 103
    BLUE_MSG_UNVERIFIED_TO_BSP_FB_VERIFIED = 104
    BLUE_MSG_UNVERIFIED_TO_BSP_PREMISE_VERIFIED = 105
    BLUE_MSG_UNVERIFIED_TO_SELF_FB_VERIFIED = 106
    BLUE_MSG_UNVERIFIED_TO_VERIFIED = 107
    BLUE_MSG_VERIFIED_TO_BSP_FB_UNVERIFIED = 108
    BLUE_MSG_VERIFIED_TO_BSP_PREMISE_UNVERIFIED = 109
    BLUE_MSG_VERIFIED_TO_SELF_FB_UNVERIFIED = 110
    BLUE_MSG_VERIFIED_TO_UNVERIFIED = 111
    BLUE_MSG_BSP_FB_UNVERIFIED_TO_BSP_PREMISE_VERIFIED = 112
    BLUE_MSG_BSP_FB_UNVERIFIED_TO_SELF_FB_VERIFIED = 113
    BLUE_MSG_BSP_FB_VERIFIED_TO_BSP_PREMISE_UNVERIFIED = 114
    BLUE_MSG_BSP_FB_VERIFIED_TO_SELF_FB_UNVERIFIED = 115
    BLUE_MSG_SELF_FB_UNVERIFIED_TO_BSP_PREMISE_VERIFIED = 116
    BLUE_MSG_SELF_FB_VERIFIED_TO_BSP_PREMISE_UNVERIFIED = 117
    E2E_IDENTITY_UNAVAILABLE = 118
    GROUP_CREATING = 119
    GROUP_CREATE_FAILED = 120
    GROUP_BOUNCED = 121
    BLOCK_CONTACT = 122
    EPHEMERAL_SETTING_NOT_APPLIED = 123
    SYNC_FAILED = 124
    SYNCING = 125
    BIZ_PRIVACY_MODE_INIT_FB = 126
    BIZ_PRIVACY_MODE_INIT_BSP = 127
    BIZ_PRIVACY_MODE_TO_FB = 128
    BIZ_PRIVACY_MODE_TO_BSP = 129


class WebMessageInfoWebMessageInfoBizPrivacyStatus(betterproto.Enum):
    E2EE = 0
    FB = 2
    BSP = 1
    BSP_AND_FB = 3


@dataclass
class AppVersion(betterproto.Message):
    primary: int = betterproto.uint32_field(1)
    secondary: int = betterproto.uint32_field(2)
    tertiary: int = betterproto.uint32_field(3)
    quaternary: int = betterproto.uint32_field(4)
    quinary: int = betterproto.uint32_field(5)


@dataclass
class UserAgent(betterproto.Message):
    platform: "UserAgentUserAgentPlatform" = betterproto.enum_field(1)
    app_version: "AppVersion" = betterproto.message_field(2)
    mcc: str = betterproto.string_field(3)
    mnc: str = betterproto.string_field(4)
    os_version: str = betterproto.string_field(5)
    manufacturer: str = betterproto.string_field(6)
    device: str = betterproto.string_field(7)
    os_build_number: str = betterproto.string_field(8)
    phone_id: str = betterproto.string_field(9)
    release_channel: "UserAgentUserAgentReleaseChannel" = betterproto.enum_field(10)
    locale_language_iso6391: str = betterproto.string_field(11)
    locale_country_iso31661_alpha2: str = betterproto.string_field(12)
    device_board: str = betterproto.string_field(13)


@dataclass
class WebdPayload(betterproto.Message):
    uses_participant_in_key: bool = betterproto.bool_field(1)
    supports_starred_messages: bool = betterproto.bool_field(2)
    supports_document_messages: bool = betterproto.bool_field(3)
    supports_url_messages: bool = betterproto.bool_field(4)
    supports_media_retry: bool = betterproto.bool_field(5)
    supports_e2_e_image: bool = betterproto.bool_field(6)
    supports_e2_e_video: bool = betterproto.bool_field(7)
    supports_e2_e_audio: bool = betterproto.bool_field(8)
    supports_e2_e_document: bool = betterproto.bool_field(9)
    document_types: str = betterproto.string_field(10)
    features: bytes = betterproto.bytes_field(11)


@dataclass
class WebInfo(betterproto.Message):
    ref_token: str = betterproto.string_field(1)
    version: str = betterproto.string_field(2)
    webd_payload: "WebdPayload" = betterproto.message_field(3)
    web_sub_platform: "WebInfoWebInfoWebSubPlatform" = betterproto.enum_field(4)


@dataclass
class DNSSource(betterproto.Message):
    dns_method: "DNSSourceDNSSourceDNSResolutionMethod" = betterproto.enum_field(15)
    app_cached: bool = betterproto.bool_field(16)


@dataclass
class CompanionRegData(betterproto.Message):
    e_regid: bytes = betterproto.bytes_field(1)
    e_keytype: bytes = betterproto.bytes_field(2)
    e_ident: bytes = betterproto.bytes_field(3)
    e_skey_id: bytes = betterproto.bytes_field(4)
    e_skey_val: bytes = betterproto.bytes_field(5)
    e_skey_sig: bytes = betterproto.bytes_field(6)
    build_hash: bytes = betterproto.bytes_field(7)
    companion_props: bytes = betterproto.bytes_field(8)


@dataclass
class ClientPayload(betterproto.Message):
    username: int = betterproto.uint64_field(1)
    passive: bool = betterproto.bool_field(3)
    client_features: List[
        "ClientPayloadClientPayloadClientFeature"
    ] = betterproto.enum_field(4)
    user_agent: "UserAgent" = betterproto.message_field(5)
    web_info: "WebInfo" = betterproto.message_field(6)
    push_name: str = betterproto.string_field(7)
    session_id: float = betterproto.sfixed32_field(9)
    short_connect: bool = betterproto.bool_field(10)
    ios_app_extension: "ClientPayloadClientPayloadIOSAppExtension" = (
        betterproto.enum_field(30)
    )
    connect_type: "ClientPayloadClientPayloadConnectType" = betterproto.enum_field(12)
    connect_reason: "ClientPayloadClientPayloadConnectReason" = betterproto.enum_field(
        13
    )
    shards: List[int] = betterproto.int32_field(14)
    dns_source: "DNSSource" = betterproto.message_field(15)
    connect_attempt_count: int = betterproto.uint32_field(16)
    agent: int = betterproto.uint32_field(17)
    device: int = betterproto.uint32_field(18)
    reg_data: "CompanionRegData" = betterproto.message_field(19)
    product: "ClientPayloadClientPayloadProduct" = betterproto.enum_field(20)
    fb_cat: bytes = betterproto.bytes_field(21)
    fb_user_agent: bytes = betterproto.bytes_field(22)
    oc: bool = betterproto.bool_field(23)


@dataclass
class Details(betterproto.Message):
    serial: int = betterproto.uint32_field(1)
    issuer: str = betterproto.string_field(2)
    expires: int = betterproto.uint64_field(3)
    subject: str = betterproto.string_field(4)
    key: bytes = betterproto.bytes_field(5)


@dataclass
class NoiseCertificate(betterproto.Message):
    details: bytes = betterproto.bytes_field(1)
    signature: bytes = betterproto.bytes_field(2)


@dataclass
class ClientHello(betterproto.Message):
    ephemeral: bytes = betterproto.bytes_field(1)
    static: bytes = betterproto.bytes_field(2)
    payload: bytes = betterproto.bytes_field(3)


@dataclass
class ServerHello(betterproto.Message):
    ephemeral: bytes = betterproto.bytes_field(1)
    static: bytes = betterproto.bytes_field(2)
    payload: bytes = betterproto.bytes_field(3)


@dataclass
class ClientFinish(betterproto.Message):
    static: bytes = betterproto.bytes_field(1)
    payload: bytes = betterproto.bytes_field(2)


@dataclass
class HandshakeMessage(betterproto.Message):
    client_hello: "ClientHello" = betterproto.message_field(2)
    server_hello: "ServerHello" = betterproto.message_field(3)
    client_finish: "ClientFinish" = betterproto.message_field(4)


@dataclass
class BizIdentityInfo(betterproto.Message):
    vlevel: "BizIdentityInfoBizIdentityInfoVerifiedLevelValue" = betterproto.enum_field(
        1
    )
    vname_cert: "VerifiedNameCertificate" = betterproto.message_field(2)
    signed: bool = betterproto.bool_field(3)
    revoked: bool = betterproto.bool_field(4)
    host_storage: "BizIdentityInfoBizIdentityInfoHostStorageType" = (
        betterproto.enum_field(5)
    )
    actual_actors: "BizIdentityInfoBizIdentityInfoActualActorsType" = (
        betterproto.enum_field(6)
    )
    privacy_mode_ts: int = betterproto.uint64_field(7)


@dataclass
class BizAccountLinkInfo(betterproto.Message):
    whatsapp_biz_acct_fbid: int = betterproto.uint64_field(1)
    whatsapp_acct_number: str = betterproto.string_field(2)
    issue_time: int = betterproto.uint64_field(3)
    host_storage: "BizAccountLinkInfoBizAccountLinkInfoHostStorageType" = (
        betterproto.enum_field(4)
    )
    account_type: "BizAccountLinkInfoBizAccountLinkInfoAccountType" = (
        betterproto.enum_field(5)
    )


@dataclass
class BizAccountPayload(betterproto.Message):
    vname_cert: "VerifiedNameCertificate" = betterproto.message_field(1)
    biz_acct_link_info: bytes = betterproto.bytes_field(2)


@dataclass
class VerifiedNameCertificate(betterproto.Message):
    details: bytes = betterproto.bytes_field(1)
    signature: bytes = betterproto.bytes_field(2)
    server_signature: bytes = betterproto.bytes_field(3)


@dataclass
class LocalizedName(betterproto.Message):
    lg: str = betterproto.string_field(1)
    lc: str = betterproto.string_field(2)
    verified_name: str = betterproto.string_field(3)


@dataclass
class SyncActionData(betterproto.Message):
    index: bytes = betterproto.bytes_field(1)
    value: "SyncActionValue" = betterproto.message_field(2)
    padding: bytes = betterproto.bytes_field(3)
    version: int = betterproto.int32_field(4)


@dataclass
class StarAction(betterproto.Message):
    starred: bool = betterproto.bool_field(1)


@dataclass
class ContactAction(betterproto.Message):
    full_name: str = betterproto.string_field(1)
    first_name: str = betterproto.string_field(2)


@dataclass
class MuteAction(betterproto.Message):
    muted: bool = betterproto.bool_field(1)
    mute_end_timestamp: int = betterproto.int64_field(2)


@dataclass
class PinAction(betterproto.Message):
    pinned: bool = betterproto.bool_field(1)


@dataclass
class SecurityNotificationSetting(betterproto.Message):
    show_notification: bool = betterproto.bool_field(1)


@dataclass
class PushNameSetting(betterproto.Message):
    name: str = betterproto.string_field(1)


@dataclass
class LocaleSetting(betterproto.Message):
    locale: str = betterproto.string_field(1)


@dataclass
class QuickReplyAction(betterproto.Message):
    shortcut: str = betterproto.string_field(1)
    message: str = betterproto.string_field(2)
    keywords: List[str] = betterproto.string_field(3)
    count: int = betterproto.int32_field(4)
    deleted: bool = betterproto.bool_field(5)


@dataclass
class LabelAssociationAction(betterproto.Message):
    labeled: bool = betterproto.bool_field(1)


@dataclass
class LabelEditAction(betterproto.Message):
    name: str = betterproto.string_field(1)
    color: int = betterproto.int32_field(2)
    predefined_id: int = betterproto.int32_field(3)
    deleted: bool = betterproto.bool_field(4)


@dataclass
class RecentStickerWeightsAction(betterproto.Message):
    weights: List["RecentStickerWeight"] = betterproto.message_field(1)


@dataclass
class RecentStickerMetadata(betterproto.Message):
    direct_path: str = betterproto.string_field(1)
    enc_filehash: str = betterproto.string_field(2)
    media_key: str = betterproto.string_field(3)
    stanza_id: str = betterproto.string_field(4)
    chat_jid: str = betterproto.string_field(5)
    participant: str = betterproto.string_field(6)
    is_sent_by_me: bool = betterproto.bool_field(7)


@dataclass
class RecentEmojiWeightsAction(betterproto.Message):
    weights: List["RecentEmojiWeight"] = betterproto.message_field(1)


@dataclass
class ArchiveChatAction(betterproto.Message):
    archived: bool = betterproto.bool_field(1)
    message_range: "SyncActionMessageRange" = betterproto.message_field(2)


@dataclass
class DeleteMessageForMeAction(betterproto.Message):
    delete_media: bool = betterproto.bool_field(1)
    message_timestamp: int = betterproto.int64_field(2)


@dataclass
class MarkChatAsReadAction(betterproto.Message):
    read: bool = betterproto.bool_field(1)
    message_range: "SyncActionMessageRange" = betterproto.message_field(2)


@dataclass
class ClearChatAction(betterproto.Message):
    message_range: "SyncActionMessageRange" = betterproto.message_field(1)


@dataclass
class DeleteChatAction(betterproto.Message):
    message_range: "SyncActionMessageRange" = betterproto.message_field(1)


@dataclass
class UnarchiveChatsSetting(betterproto.Message):
    unarchive_chats: bool = betterproto.bool_field(1)


@dataclass
class SyncActionMessageRange(betterproto.Message):
    last_message_timestamp: int = betterproto.int64_field(1)
    last_system_message_timestamp: int = betterproto.int64_field(2)
    messages: List["SyncActionMessage"] = betterproto.message_field(3)


@dataclass
class SyncActionMessage(betterproto.Message):
    key: "MessageKey" = betterproto.message_field(1)
    timestamp: int = betterproto.int64_field(2)


@dataclass
class KeyExpiration(betterproto.Message):
    expired_key_epoch: int = betterproto.int32_field(1)


@dataclass
class SyncActionValue(betterproto.Message):
    timestamp: int = betterproto.int64_field(1)
    star_action: "StarAction" = betterproto.message_field(2)
    contact_action: "ContactAction" = betterproto.message_field(3)
    mute_action: "MuteAction" = betterproto.message_field(4)
    pin_action: "PinAction" = betterproto.message_field(5)
    security_notification_setting: "SecurityNotificationSetting" = (
        betterproto.message_field(6)
    )
    push_name_setting: "PushNameSetting" = betterproto.message_field(7)
    quick_reply_action: "QuickReplyAction" = betterproto.message_field(8)
    recent_sticker_weights_action: "RecentStickerWeightsAction" = (
        betterproto.message_field(9)
    )
    recent_sticker_metadata: "RecentStickerMetadata" = betterproto.message_field(10)
    recent_emoji_weights_action: "RecentEmojiWeightsAction" = betterproto.message_field(
        11
    )
    label_edit_action: "LabelEditAction" = betterproto.message_field(14)
    label_association_action: "LabelAssociationAction" = betterproto.message_field(15)
    locale_setting: "LocaleSetting" = betterproto.message_field(16)
    archive_chat_action: "ArchiveChatAction" = betterproto.message_field(17)
    delete_message_for_me_action: "DeleteMessageForMeAction" = (
        betterproto.message_field(18)
    )
    key_expiration: "KeyExpiration" = betterproto.message_field(19)
    mark_chat_as_read_action: "MarkChatAsReadAction" = betterproto.message_field(20)
    clear_chat_action: "ClearChatAction" = betterproto.message_field(21)
    delete_chat_action: "DeleteChatAction" = betterproto.message_field(22)
    unarchive_chats_setting: "UnarchiveChatsSetting" = betterproto.message_field(23)


@dataclass
class RecentEmojiWeight(betterproto.Message):
    emoji: str = betterproto.string_field(1)
    weight: float = betterproto.float_field(2)


@dataclass
class RecentStickerWeight(betterproto.Message):
    filehash: str = betterproto.string_field(1)
    weight: float = betterproto.float_field(2)


@dataclass
class SyncdPatch(betterproto.Message):
    version: "SyncdVersion" = betterproto.message_field(1)
    mutations: List["SyncdMutation"] = betterproto.message_field(2)
    external_mutations: "ExternalBlobReference" = betterproto.message_field(3)
    snapshot_mac: bytes = betterproto.bytes_field(4)
    patch_mac: bytes = betterproto.bytes_field(5)
    key_id: "KeyId" = betterproto.message_field(6)
    exit_code: "ExitCode" = betterproto.message_field(7)
    device_index: int = betterproto.uint32_field(8)


@dataclass
class SyncdMutation(betterproto.Message):
    operation: "SyncdMutationSyncdMutationSyncdOperation" = betterproto.enum_field(1)
    record: "SyncdRecord" = betterproto.message_field(2)


@dataclass
class SyncdMutations(betterproto.Message):
    mutations: List["SyncdMutation"] = betterproto.message_field(1)


@dataclass
class SyncdSnapshot(betterproto.Message):
    version: "SyncdVersion" = betterproto.message_field(1)
    records: List["SyncdRecord"] = betterproto.message_field(2)
    mac: bytes = betterproto.bytes_field(3)
    key_id: "KeyId" = betterproto.message_field(4)


@dataclass
class ExternalBlobReference(betterproto.Message):
    media_key: bytes = betterproto.bytes_field(1)
    direct_path: str = betterproto.string_field(2)
    handle: str = betterproto.string_field(3)
    file_size_bytes: int = betterproto.uint64_field(4)
    file_sha256: bytes = betterproto.bytes_field(5)
    file_enc_sha256: bytes = betterproto.bytes_field(6)


@dataclass
class SyncdRecord(betterproto.Message):
    index: "SyncdIndex" = betterproto.message_field(1)
    value: "SyncdValue" = betterproto.message_field(2)
    key_id: "KeyId" = betterproto.message_field(3)


@dataclass
class KeyId(betterproto.Message):
    id: bytes = betterproto.bytes_field(1)


@dataclass
class SyncdValue(betterproto.Message):
    blob: bytes = betterproto.bytes_field(1)


@dataclass
class SyncdIndex(betterproto.Message):
    blob: bytes = betterproto.bytes_field(1)


@dataclass
class ExitCode(betterproto.Message):
    code: int = betterproto.uint64_field(1)
    text: str = betterproto.string_field(2)


@dataclass
class SyncdVersion(betterproto.Message):
    version: int = betterproto.uint64_field(1)


@dataclass
class ServerErrorReceipt(betterproto.Message):
    stanza_id: str = betterproto.string_field(1)


@dataclass
class MediaRetryNotification(betterproto.Message):
    stanza_id: str = betterproto.string_field(1)
    direct_path: str = betterproto.string_field(2)
    result: "MediaRetryNotificationMediaRetryNotificationResultType" = (
        betterproto.enum_field(3)
    )


@dataclass
class MsgOpaqueData(betterproto.Message):
    body: str = betterproto.string_field(1)
    caption: str = betterproto.string_field(3)
    client_url: str = betterproto.string_field(4)
    # optional string loc = 4;
    lng: float = betterproto.double_field(5)
    lat: float = betterproto.double_field(7)
    payment_amount1000: int = betterproto.int32_field(8)
    payment_note_msg_body: str = betterproto.string_field(9)
    canonical_url: str = betterproto.string_field(10)
    matched_text: str = betterproto.string_field(11)
    title: str = betterproto.string_field(12)
    description: str = betterproto.string_field(13)


@dataclass
class MsgRowOpaqueData(betterproto.Message):
    current_msg: "MsgOpaqueData" = betterproto.message_field(1)
    quoted_msg: "MsgOpaqueData" = betterproto.message_field(2)


@dataclass
class Pushname(betterproto.Message):
    id: str = betterproto.string_field(1)
    pushname: str = betterproto.string_field(2)


@dataclass
class HistorySyncMsg(betterproto.Message):
    message: "WebMessageInfo" = betterproto.message_field(1)
    msg_order_id: int = betterproto.uint64_field(2)


@dataclass
class Conversation(betterproto.Message):
    id: str = betterproto.string_field(1)
    messages: List["HistorySyncMsg"] = betterproto.message_field(2)
    new_jid: str = betterproto.string_field(3)
    old_jid: str = betterproto.string_field(4)
    last_msg_timestamp: int = betterproto.uint64_field(5)
    unread_count: int = betterproto.uint32_field(6)
    read_only: bool = betterproto.bool_field(7)
    end_of_history_transfer: bool = betterproto.bool_field(8)
    ephemeral_expiration: int = betterproto.uint32_field(9)
    ephemeral_setting_timestamp: int = betterproto.int64_field(10)
    end_of_history_transfer_type: "ConversationConversationEndOfHistoryTransferType" = (
        betterproto.enum_field(11)
    )
    conversation_timestamp: int = betterproto.uint64_field(12)
    name: str = betterproto.string_field(13)
    p_hash: str = betterproto.string_field(14)
    not_spam: bool = betterproto.bool_field(15)


@dataclass
class HistorySync(betterproto.Message):
    sync_type: "HistorySyncHistorySyncHistorySyncType" = betterproto.enum_field(1)
    conversations: List["Conversation"] = betterproto.message_field(2)
    status_v3_messages: List["WebMessageInfo"] = betterproto.message_field(3)
    chunk_order: int = betterproto.uint32_field(5)
    progress: int = betterproto.uint32_field(6)
    pushnames: List["Pushname"] = betterproto.message_field(7)


@dataclass
class EphemeralSetting(betterproto.Message):
    duration: float = betterproto.sfixed32_field(1)
    timestamp: float = betterproto.sfixed64_field(2)


@dataclass
class PaymentBackground(betterproto.Message):
    id: str = betterproto.string_field(1)
    file_length: str = betterproto.string_field(2)
    width: int = betterproto.uint32_field(3)
    height: int = betterproto.uint32_field(4)
    mimetype: str = betterproto.string_field(5)
    placeholder_argb: float = betterproto.fixed32_field(6)
    text_argb: float = betterproto.fixed32_field(7)
    subtext_argb: float = betterproto.fixed32_field(8)


@dataclass
class Money(betterproto.Message):
    value: int = betterproto.int64_field(1)
    offset: int = betterproto.uint32_field(2)
    currency_code: str = betterproto.string_field(3)


@dataclass
class HydratedQuickReplyButton(betterproto.Message):
    display_text: str = betterproto.string_field(1)
    id: str = betterproto.string_field(2)


@dataclass
class HydratedURLButton(betterproto.Message):
    display_text: str = betterproto.string_field(1)
    url: str = betterproto.string_field(2)


@dataclass
class HydratedCallButton(betterproto.Message):
    display_text: str = betterproto.string_field(1)
    phone_number: str = betterproto.string_field(2)


@dataclass
class HydratedTemplateButton(betterproto.Message):
    index: int = betterproto.uint32_field(4)
    quick_reply_button: "HydratedQuickReplyButton" = betterproto.message_field(
        1, group="hydratedButton"
    )
    url_button: "HydratedURLButton" = betterproto.message_field(
        2, group="hydratedButton"
    )
    call_button: "HydratedCallButton" = betterproto.message_field(
        3, group="hydratedButton"
    )


@dataclass
class QuickReplyButton(betterproto.Message):
    display_text: "HighlyStructuredMessage" = betterproto.message_field(1)
    id: str = betterproto.string_field(2)


@dataclass
class URLButton(betterproto.Message):
    display_text: "HighlyStructuredMessage" = betterproto.message_field(1)
    url: "HighlyStructuredMessage" = betterproto.message_field(2)


@dataclass
class CallButton(betterproto.Message):
    display_text: "HighlyStructuredMessage" = betterproto.message_field(1)
    phone_number: "HighlyStructuredMessage" = betterproto.message_field(2)


@dataclass
class TemplateButton(betterproto.Message):
    index: int = betterproto.uint32_field(4)
    quick_reply_button: "QuickReplyButton" = betterproto.message_field(
        1, group="button"
    )
    url_button: "URLButton" = betterproto.message_field(2, group="button")
    call_button: "CallButton" = betterproto.message_field(3, group="button")


@dataclass
class Location(betterproto.Message):
    degrees_latitude: float = betterproto.double_field(1)
    degrees_longitude: float = betterproto.double_field(2)
    name: str = betterproto.string_field(3)


@dataclass
class Point(betterproto.Message):
    x_deprecated: int = betterproto.int32_field(1)
    y_deprecated: int = betterproto.int32_field(2)
    x: float = betterproto.double_field(3)
    y: float = betterproto.double_field(4)


@dataclass
class InteractiveAnnotation(betterproto.Message):
    polygon_vertices: List["Point"] = betterproto.message_field(1)
    location: "Location" = betterproto.message_field(2, group="action")


@dataclass
class DeviceListMetadata(betterproto.Message):
    sender_key_hash: bytes = betterproto.bytes_field(1)
    sender_timestamp: int = betterproto.uint64_field(2)
    sender_key_indexes: List[int] = betterproto.uint32_field(3)
    recipient_key_hash: bytes = betterproto.bytes_field(8)
    recipient_timestamp: int = betterproto.uint64_field(9)
    recipient_key_indexes: List[int] = betterproto.uint32_field(10)


@dataclass
class MessageContextInfo(betterproto.Message):
    device_list_metadata: "DeviceListMetadata" = betterproto.message_field(1)
    device_list_metadata_version: int = betterproto.int32_field(2)


@dataclass
class AdReplyInfo(betterproto.Message):
    advertiser_name: str = betterproto.string_field(1)
    media_type: "AdReplyInfoAdReplyInfoMediaType" = betterproto.enum_field(2)
    jpeg_thumbnail: bytes = betterproto.bytes_field(16)
    caption: str = betterproto.string_field(17)


@dataclass
class ExternalAdReplyInfo(betterproto.Message):
    title: str = betterproto.string_field(1)
    body: str = betterproto.string_field(2)
    media_type: "ExternalAdReplyInfoExternalAdReplyInfoMediaType" = (
        betterproto.enum_field(3)
    )
    thumbnail_url: str = betterproto.string_field(4)
    media_url: str = betterproto.string_field(5)
    thumbnail: bytes = betterproto.bytes_field(6)
    source_type: str = betterproto.string_field(7)
    source_id: str = betterproto.string_field(8)
    source_url: str = betterproto.string_field(9)


@dataclass
class ContextInfo(betterproto.Message):
    stanza_id: str = betterproto.string_field(1)
    participant: str = betterproto.string_field(2)
    quoted_message: "Message" = betterproto.message_field(3)
    remote_jid: str = betterproto.string_field(4)
    mentioned_jid: List[str] = betterproto.string_field(15)
    conversion_source: str = betterproto.string_field(18)
    conversion_data: bytes = betterproto.bytes_field(19)
    conversion_delay_seconds: int = betterproto.uint32_field(20)
    forwarding_score: int = betterproto.uint32_field(21)
    is_forwarded: bool = betterproto.bool_field(22)
    quoted_ad: "AdReplyInfo" = betterproto.message_field(23)
    placeholder_key: "MessageKey" = betterproto.message_field(24)
    expiration: int = betterproto.uint32_field(25)
    ephemeral_setting_timestamp: int = betterproto.int64_field(26)
    ephemeral_shared_secret: bytes = betterproto.bytes_field(27)
    external_ad_reply: "ExternalAdReplyInfo" = betterproto.message_field(28)
    entry_point_conversion_source: str = betterproto.string_field(29)
    entry_point_conversion_app: str = betterproto.string_field(30)
    entry_point_conversion_delay_seconds: int = betterproto.uint32_field(31)


@dataclass
class SenderKeyDistributionMessage(betterproto.Message):
    group_id: str = betterproto.string_field(1)
    axolotl_sender_key_distribution_message: bytes = betterproto.bytes_field(2)


@dataclass
class ImageMessage(betterproto.Message):
    url: str = betterproto.string_field(1)
    mimetype: str = betterproto.string_field(2)
    caption: str = betterproto.string_field(3)
    file_sha256: bytes = betterproto.bytes_field(4)
    file_length: int = betterproto.uint64_field(5)
    height: int = betterproto.uint32_field(6)
    width: int = betterproto.uint32_field(7)
    media_key: bytes = betterproto.bytes_field(8)
    file_enc_sha256: bytes = betterproto.bytes_field(9)
    interactive_annotations: List["InteractiveAnnotation"] = betterproto.message_field(
        10
    )
    direct_path: str = betterproto.string_field(11)
    media_key_timestamp: int = betterproto.int64_field(12)
    jpeg_thumbnail: bytes = betterproto.bytes_field(16)
    context_info: "ContextInfo" = betterproto.message_field(17)
    first_scan_sidecar: bytes = betterproto.bytes_field(18)
    first_scan_length: int = betterproto.uint32_field(19)
    experiment_group_id: int = betterproto.uint32_field(20)
    scans_sidecar: bytes = betterproto.bytes_field(21)
    scan_lengths: List[int] = betterproto.uint32_field(22)
    mid_quality_file_sha256: bytes = betterproto.bytes_field(23)
    mid_quality_file_enc_sha256: bytes = betterproto.bytes_field(24)
    view_once: bool = betterproto.bool_field(25)
    thumbnail_direct_path: str = betterproto.string_field(26)
    thumbnail_sha256: bytes = betterproto.bytes_field(27)
    thumbnail_enc_sha256: bytes = betterproto.bytes_field(28)


@dataclass
class InvoiceMessage(betterproto.Message):
    note: str = betterproto.string_field(1)
    token: str = betterproto.string_field(2)
    attachment_type: "InvoiceMessageInvoiceMessageAttachmentType" = (
        betterproto.enum_field(3)
    )
    attachment_mimetype: str = betterproto.string_field(4)
    attachment_media_key: bytes = betterproto.bytes_field(5)
    attachment_media_key_timestamp: int = betterproto.int64_field(6)
    attachment_file_sha256: bytes = betterproto.bytes_field(7)
    attachment_file_enc_sha256: bytes = betterproto.bytes_field(8)
    attachment_direct_path: str = betterproto.string_field(9)
    attachment_jpeg_thumbnail: bytes = betterproto.bytes_field(10)


@dataclass
class ContactMessage(betterproto.Message):
    display_name: str = betterproto.string_field(1)
    vcard: str = betterproto.string_field(16)
    context_info: "ContextInfo" = betterproto.message_field(17)


@dataclass
class LocationMessage(betterproto.Message):
    degrees_latitude: float = betterproto.double_field(1)
    degrees_longitude: float = betterproto.double_field(2)
    name: str = betterproto.string_field(3)
    address: str = betterproto.string_field(4)
    url: str = betterproto.string_field(5)
    is_live: bool = betterproto.bool_field(6)
    accuracy_in_meters: int = betterproto.uint32_field(7)
    speed_in_mps: float = betterproto.float_field(8)
    degrees_clockwise_from_magnetic_north: int = betterproto.uint32_field(9)
    comment: str = betterproto.string_field(11)
    jpeg_thumbnail: bytes = betterproto.bytes_field(16)
    context_info: "ContextInfo" = betterproto.message_field(17)


@dataclass
class ExtendedTextMessage(betterproto.Message):
    text: str = betterproto.string_field(1)
    matched_text: str = betterproto.string_field(2)
    canonical_url: str = betterproto.string_field(4)
    description: str = betterproto.string_field(5)
    title: str = betterproto.string_field(6)
    text_argb: float = betterproto.fixed32_field(7)
    background_argb: float = betterproto.fixed32_field(8)
    font: "ExtendedTextMessageExtendedTextMessageFontType" = betterproto.enum_field(9)
    preview_type: "ExtendedTextMessageExtendedTextMessagePreviewType" = (
        betterproto.enum_field(10)
    )
    jpeg_thumbnail: bytes = betterproto.bytes_field(16)
    context_info: "ContextInfo" = betterproto.message_field(17)
    do_not_play_inline: bool = betterproto.bool_field(18)
    thumbnail_direct_path: str = betterproto.string_field(19)
    thumbnail_sha256: bytes = betterproto.bytes_field(20)
    thumbnail_enc_sha256: bytes = betterproto.bytes_field(21)
    media_key: bytes = betterproto.bytes_field(22)
    media_key_timestamp: int = betterproto.int64_field(23)
    thumbnail_height: int = betterproto.uint32_field(24)
    thumbnail_width: int = betterproto.uint32_field(25)


@dataclass
class DocumentMessage(betterproto.Message):
    url: str = betterproto.string_field(1)
    mimetype: str = betterproto.string_field(2)
    title: str = betterproto.string_field(3)
    file_sha256: bytes = betterproto.bytes_field(4)
    file_length: int = betterproto.uint64_field(5)
    page_count: int = betterproto.uint32_field(6)
    media_key: bytes = betterproto.bytes_field(7)
    file_name: str = betterproto.string_field(8)
    file_enc_sha256: bytes = betterproto.bytes_field(9)
    direct_path: str = betterproto.string_field(10)
    media_key_timestamp: int = betterproto.int64_field(11)
    contact_vcard: bool = betterproto.bool_field(12)
    thumbnail_direct_path: str = betterproto.string_field(13)
    thumbnail_sha256: bytes = betterproto.bytes_field(14)
    thumbnail_enc_sha256: bytes = betterproto.bytes_field(15)
    jpeg_thumbnail: bytes = betterproto.bytes_field(16)
    context_info: "ContextInfo" = betterproto.message_field(17)
    thumbnail_height: int = betterproto.uint32_field(18)
    thumbnail_width: int = betterproto.uint32_field(19)


@dataclass
class AudioMessage(betterproto.Message):
    url: str = betterproto.string_field(1)
    mimetype: str = betterproto.string_field(2)
    file_sha256: bytes = betterproto.bytes_field(3)
    file_length: int = betterproto.uint64_field(4)
    seconds: int = betterproto.uint32_field(5)
    ptt: bool = betterproto.bool_field(6)
    media_key: bytes = betterproto.bytes_field(7)
    file_enc_sha256: bytes = betterproto.bytes_field(8)
    direct_path: str = betterproto.string_field(9)
    media_key_timestamp: int = betterproto.int64_field(10)
    context_info: "ContextInfo" = betterproto.message_field(17)
    streaming_sidecar: bytes = betterproto.bytes_field(18)


@dataclass
class VideoMessage(betterproto.Message):
    url: str = betterproto.string_field(1)
    mimetype: str = betterproto.string_field(2)
    file_sha256: bytes = betterproto.bytes_field(3)
    file_length: int = betterproto.uint64_field(4)
    seconds: int = betterproto.uint32_field(5)
    media_key: bytes = betterproto.bytes_field(6)
    caption: str = betterproto.string_field(7)
    gif_playback: bool = betterproto.bool_field(8)
    height: int = betterproto.uint32_field(9)
    width: int = betterproto.uint32_field(10)
    file_enc_sha256: bytes = betterproto.bytes_field(11)
    interactive_annotations: List["InteractiveAnnotation"] = betterproto.message_field(
        12
    )
    direct_path: str = betterproto.string_field(13)
    media_key_timestamp: int = betterproto.int64_field(14)
    jpeg_thumbnail: bytes = betterproto.bytes_field(16)
    context_info: "ContextInfo" = betterproto.message_field(17)
    streaming_sidecar: bytes = betterproto.bytes_field(18)
    gif_attribution: "VideoMessageVideoMessageAttribution" = betterproto.enum_field(19)
    view_once: bool = betterproto.bool_field(20)
    thumbnail_direct_path: str = betterproto.string_field(21)
    thumbnail_sha256: bytes = betterproto.bytes_field(22)
    thumbnail_enc_sha256: bytes = betterproto.bytes_field(23)


@dataclass
class Call(betterproto.Message):
    call_key: bytes = betterproto.bytes_field(1)
    conversion_source: str = betterproto.string_field(2)
    conversion_data: bytes = betterproto.bytes_field(3)
    conversion_delay_seconds: int = betterproto.uint32_field(4)


@dataclass
class Chat(betterproto.Message):
    display_name: str = betterproto.string_field(1)
    id: str = betterproto.string_field(2)


@dataclass
class ProtocolMessage(betterproto.Message):
    key: "MessageKey" = betterproto.message_field(1)
    type: "ProtocolMessageProtocolMessageType" = betterproto.enum_field(2)
    ephemeral_expiration: int = betterproto.uint32_field(4)
    ephemeral_setting_timestamp: int = betterproto.int64_field(5)
    history_sync_notification: "HistorySyncNotification" = betterproto.message_field(6)
    app_state_sync_key_share: "AppStateSyncKeyShare" = betterproto.message_field(7)
    app_state_sync_key_request: "AppStateSyncKeyRequest" = betterproto.message_field(8)
    initial_security_notification_setting_sync: "InitialSecurityNotificationSettingSync" = betterproto.message_field(
        9
    )
    app_state_fatal_exception_notification: "AppStateFatalExceptionNotification" = (
        betterproto.message_field(10)
    )


@dataclass
class HistorySyncNotification(betterproto.Message):
    file_sha256: bytes = betterproto.bytes_field(1)
    file_length: int = betterproto.uint64_field(2)
    media_key: bytes = betterproto.bytes_field(3)
    file_enc_sha256: bytes = betterproto.bytes_field(4)
    direct_path: str = betterproto.string_field(5)
    sync_type: "HistorySyncNotificationHistorySyncNotificationHistorySyncType" = (
        betterproto.enum_field(6)
    )
    chunk_order: int = betterproto.uint32_field(7)
    original_message_id: str = betterproto.string_field(8)


@dataclass
class AppStateSyncKey(betterproto.Message):
    key_id: "AppStateSyncKeyId" = betterproto.message_field(1)
    key_data: "AppStateSyncKeyData" = betterproto.message_field(2)


@dataclass
class AppStateSyncKeyId(betterproto.Message):
    key_id: bytes = betterproto.bytes_field(1)


@dataclass
class AppStateSyncKeyFingerprint(betterproto.Message):
    raw_id: int = betterproto.uint32_field(1)
    current_index: int = betterproto.uint32_field(2)
    device_indexes: List[int] = betterproto.uint32_field(3)


@dataclass
class AppStateSyncKeyData(betterproto.Message):
    key_data: bytes = betterproto.bytes_field(1)
    fingerprint: "AppStateSyncKeyFingerprint" = betterproto.message_field(2)
    timestamp: int = betterproto.int64_field(3)


@dataclass
class AppStateSyncKeyShare(betterproto.Message):
    keys: List["AppStateSyncKey"] = betterproto.message_field(1)


@dataclass
class AppStateSyncKeyRequest(betterproto.Message):
    key_ids: List["AppStateSyncKeyId"] = betterproto.message_field(1)


@dataclass
class AppStateFatalExceptionNotification(betterproto.Message):
    collection_names: List[str] = betterproto.string_field(1)
    timestamp: int = betterproto.int64_field(2)


@dataclass
class InitialSecurityNotificationSettingSync(betterproto.Message):
    security_notification_enabled: bool = betterproto.bool_field(1)


@dataclass
class ContactsArrayMessage(betterproto.Message):
    display_name: str = betterproto.string_field(1)
    contacts: List["ContactMessage"] = betterproto.message_field(2)
    context_info: "ContextInfo" = betterproto.message_field(17)


@dataclass
class HSMCurrency(betterproto.Message):
    currency_code: str = betterproto.string_field(1)
    amount1000: int = betterproto.int64_field(2)


@dataclass
class HSMDateTimeComponent(betterproto.Message):
    day_of_week: "HSMDateTimeComponentHSMDateTimeComponentDayOfWeekType" = (
        betterproto.enum_field(1)
    )
    year: int = betterproto.uint32_field(2)
    month: int = betterproto.uint32_field(3)
    day_of_month: int = betterproto.uint32_field(4)
    hour: int = betterproto.uint32_field(5)
    minute: int = betterproto.uint32_field(6)
    calendar: "HSMDateTimeComponentHSMDateTimeComponentCalendarType" = (
        betterproto.enum_field(7)
    )


@dataclass
class HSMDateTimeUnixEpoch(betterproto.Message):
    timestamp: int = betterproto.int64_field(1)


@dataclass
class HSMDateTime(betterproto.Message):
    component: "HSMDateTimeComponent" = betterproto.message_field(
        1, group="datetimeOneof"
    )
    unix_epoch: "HSMDateTimeUnixEpoch" = betterproto.message_field(
        2, group="datetimeOneof"
    )


@dataclass
class HSMLocalizableParameter(betterproto.Message):
    default: str = betterproto.string_field(1)
    currency: "HSMCurrency" = betterproto.message_field(2, group="paramOneof")
    date_time: "HSMDateTime" = betterproto.message_field(3, group="paramOneof")


@dataclass
class HighlyStructuredMessage(betterproto.Message):
    namespace: str = betterproto.string_field(1)
    element_name: str = betterproto.string_field(2)
    params: List[str] = betterproto.string_field(3)
    fallback_lg: str = betterproto.string_field(4)
    fallback_lc: str = betterproto.string_field(5)
    localizable_params: List["HSMLocalizableParameter"] = betterproto.message_field(6)
    deterministic_lg: str = betterproto.string_field(7)
    deterministic_lc: str = betterproto.string_field(8)
    hydrated_hsm: "TemplateMessage" = betterproto.message_field(9)


@dataclass
class SendPaymentMessage(betterproto.Message):
    note_message: "Message" = betterproto.message_field(2)
    request_message_key: "MessageKey" = betterproto.message_field(3)
    background: "PaymentBackground" = betterproto.message_field(4)


@dataclass
class RequestPaymentMessage(betterproto.Message):
    note_message: "Message" = betterproto.message_field(4)
    currency_code_iso4217: str = betterproto.string_field(1)
    amount1000: int = betterproto.uint64_field(2)
    request_from: str = betterproto.string_field(3)
    expiry_timestamp: int = betterproto.int64_field(5)
    amount: "Money" = betterproto.message_field(6)
    background: "PaymentBackground" = betterproto.message_field(7)


@dataclass
class DeclinePaymentRequestMessage(betterproto.Message):
    key: "MessageKey" = betterproto.message_field(1)


@dataclass
class CancelPaymentRequestMessage(betterproto.Message):
    key: "MessageKey" = betterproto.message_field(1)


@dataclass
class PaymentInviteMessage(betterproto.Message):
    service_type: "PaymentInviteMessagePaymentInviteMessageServiceType" = (
        betterproto.enum_field(1)
    )
    expiry_timestamp: int = betterproto.int64_field(2)


@dataclass
class LiveLocationMessage(betterproto.Message):
    degrees_latitude: float = betterproto.double_field(1)
    degrees_longitude: float = betterproto.double_field(2)
    accuracy_in_meters: int = betterproto.uint32_field(3)
    speed_in_mps: float = betterproto.float_field(4)
    degrees_clockwise_from_magnetic_north: int = betterproto.uint32_field(5)
    caption: str = betterproto.string_field(6)
    sequence_number: int = betterproto.int64_field(7)
    time_offset: int = betterproto.uint32_field(8)
    jpeg_thumbnail: bytes = betterproto.bytes_field(16)
    context_info: "ContextInfo" = betterproto.message_field(17)


@dataclass
class StickerMessage(betterproto.Message):
    url: str = betterproto.string_field(1)
    file_sha256: bytes = betterproto.bytes_field(2)
    file_enc_sha256: bytes = betterproto.bytes_field(3)
    media_key: bytes = betterproto.bytes_field(4)
    mimetype: str = betterproto.string_field(5)
    height: int = betterproto.uint32_field(6)
    width: int = betterproto.uint32_field(7)
    direct_path: str = betterproto.string_field(8)
    file_length: int = betterproto.uint64_field(9)
    media_key_timestamp: int = betterproto.int64_field(10)
    first_frame_length: int = betterproto.uint32_field(11)
    first_frame_sidecar: bytes = betterproto.bytes_field(12)
    is_animated: bool = betterproto.bool_field(13)
    png_thumbnail: bytes = betterproto.bytes_field(16)
    context_info: "ContextInfo" = betterproto.message_field(17)


@dataclass
class FourRowTemplate(betterproto.Message):
    content: "HighlyStructuredMessage" = betterproto.message_field(6)
    footer: "HighlyStructuredMessage" = betterproto.message_field(7)
    buttons: List["TemplateButton"] = betterproto.message_field(8)
    document_message: "DocumentMessage" = betterproto.message_field(1, group="title")
    highly_structured_message: "HighlyStructuredMessage" = betterproto.message_field(
        2, group="title"
    )
    image_message: "ImageMessage" = betterproto.message_field(3, group="title")
    video_message: "VideoMessage" = betterproto.message_field(4, group="title")
    location_message: "LocationMessage" = betterproto.message_field(5, group="title")


@dataclass
class HydratedFourRowTemplate(betterproto.Message):
    hydrated_content_text: str = betterproto.string_field(6)
    hydrated_footer_text: str = betterproto.string_field(7)
    hydrated_buttons: List["HydratedTemplateButton"] = betterproto.message_field(8)
    template_id: str = betterproto.string_field(9)
    document_message: "DocumentMessage" = betterproto.message_field(1, group="title")
    hydrated_title_text: str = betterproto.string_field(2, group="title")
    image_message: "ImageMessage" = betterproto.message_field(3, group="title")
    video_message: "VideoMessage" = betterproto.message_field(4, group="title")
    location_message: "LocationMessage" = betterproto.message_field(5, group="title")


@dataclass
class TemplateMessage(betterproto.Message):
    context_info: "ContextInfo" = betterproto.message_field(3)
    hydrated_template: "HydratedFourRowTemplate" = betterproto.message_field(4)
    four_row_template: "FourRowTemplate" = betterproto.message_field(1, group="format")
    hydrated_four_row_template: "HydratedFourRowTemplate" = betterproto.message_field(
        2, group="format"
    )


@dataclass
class TemplateButtonReplyMessage(betterproto.Message):
    selected_id: str = betterproto.string_field(1)
    selected_display_text: str = betterproto.string_field(2)
    context_info: "ContextInfo" = betterproto.message_field(3)
    selected_index: int = betterproto.uint32_field(4)


@dataclass
class CatalogSnapshot(betterproto.Message):
    catalog_image: "ImageMessage" = betterproto.message_field(1)
    title: str = betterproto.string_field(2)
    description: str = betterproto.string_field(3)


@dataclass
class ProductSnapshot(betterproto.Message):
    product_image: "ImageMessage" = betterproto.message_field(1)
    product_id: str = betterproto.string_field(2)
    title: str = betterproto.string_field(3)
    description: str = betterproto.string_field(4)
    currency_code: str = betterproto.string_field(5)
    price_amount1000: int = betterproto.int64_field(6)
    retailer_id: str = betterproto.string_field(7)
    url: str = betterproto.string_field(8)
    product_image_count: int = betterproto.uint32_field(9)
    first_image_id: str = betterproto.string_field(11)
    sale_price_amount1000: int = betterproto.int64_field(12)


@dataclass
class ProductMessage(betterproto.Message):
    product: "ProductSnapshot" = betterproto.message_field(1)
    business_owner_jid: str = betterproto.string_field(2)
    catalog: "CatalogSnapshot" = betterproto.message_field(4)
    context_info: "ContextInfo" = betterproto.message_field(17)


@dataclass
class OrderMessage(betterproto.Message):
    order_id: str = betterproto.string_field(1)
    thumbnail: bytes = betterproto.bytes_field(2)
    item_count: int = betterproto.int32_field(3)
    status: "OrderMessageOrderMessageOrderStatus" = betterproto.enum_field(4)
    surface: "OrderMessageOrderMessageOrderSurface" = betterproto.enum_field(5)
    message: str = betterproto.string_field(6)
    order_title: str = betterproto.string_field(7)
    seller_jid: str = betterproto.string_field(8)
    token: str = betterproto.string_field(9)
    total_amount1000: int = betterproto.int64_field(10)
    total_currency_code: str = betterproto.string_field(11)
    context_info: "ContextInfo" = betterproto.message_field(17)


@dataclass
class Row(betterproto.Message):
    title: str = betterproto.string_field(1)
    description: str = betterproto.string_field(2)
    row_id: str = betterproto.string_field(3)


@dataclass
class Section(betterproto.Message):
    title: str = betterproto.string_field(1)
    rows: List["Row"] = betterproto.message_field(2)


@dataclass
class Product(betterproto.Message):
    product_id: str = betterproto.string_field(1)


@dataclass
class ProductSection(betterproto.Message):
    title: str = betterproto.string_field(1)
    products: List["Product"] = betterproto.message_field(2)


@dataclass
class ProductListHeaderImage(betterproto.Message):
    product_id: str = betterproto.string_field(1)
    jpeg_thumbnail: bytes = betterproto.bytes_field(2)


@dataclass
class ProductListInfo(betterproto.Message):
    product_sections: List["ProductSection"] = betterproto.message_field(1)
    header_image: "ProductListHeaderImage" = betterproto.message_field(2)
    business_owner_jid: str = betterproto.string_field(3)


@dataclass
class ListMessage(betterproto.Message):
    title: str = betterproto.string_field(1)
    description: str = betterproto.string_field(2)
    button_text: str = betterproto.string_field(3)
    list_type: "ListMessageListMessageListType" = betterproto.enum_field(4)
    sections: List["Section"] = betterproto.message_field(5)
    product_list_info: "ProductListInfo" = betterproto.message_field(6)
    footer_text: str = betterproto.string_field(7)
    context_info: "ContextInfo" = betterproto.message_field(8)


@dataclass
class SingleSelectReply(betterproto.Message):
    selected_row_id: str = betterproto.string_field(1)


@dataclass
class ListResponseMessage(betterproto.Message):
    title: str = betterproto.string_field(1)
    list_type: "ListResponseMessageListResponseMessageListType" = (
        betterproto.enum_field(2)
    )
    single_select_reply: "SingleSelectReply" = betterproto.message_field(3)
    context_info: "ContextInfo" = betterproto.message_field(4)
    description: str = betterproto.string_field(5)


@dataclass
class GroupInviteMessage(betterproto.Message):
    group_jid: str = betterproto.string_field(1)
    invite_code: str = betterproto.string_field(2)
    invite_expiration: int = betterproto.int64_field(3)
    group_name: str = betterproto.string_field(4)
    jpeg_thumbnail: bytes = betterproto.bytes_field(5)
    caption: str = betterproto.string_field(6)
    context_info: "ContextInfo" = betterproto.message_field(7)


@dataclass
class DeviceSentMessage(betterproto.Message):
    destination_jid: str = betterproto.string_field(1)
    message: "Message" = betterproto.message_field(2)
    phash: str = betterproto.string_field(3)


@dataclass
class FutureProofMessage(betterproto.Message):
    message: "Message" = betterproto.message_field(1)


@dataclass
class ButtonText(betterproto.Message):
    display_text: str = betterproto.string_field(1)


@dataclass
class NativeFlowInfo(betterproto.Message):
    name: str = betterproto.string_field(1)
    params_json: str = betterproto.string_field(2)


@dataclass
class Button(betterproto.Message):
    button_id: str = betterproto.string_field(1)
    button_text: "ButtonText" = betterproto.message_field(2)
    type: "ButtonButtonType" = betterproto.enum_field(3)
    native_flow_info: "NativeFlowInfo" = betterproto.message_field(4)


@dataclass
class ButtonsMessage(betterproto.Message):
    content_text: str = betterproto.string_field(6)
    footer_text: str = betterproto.string_field(7)
    context_info: "ContextInfo" = betterproto.message_field(8)
    buttons: List["Button"] = betterproto.message_field(9)
    header_type: "ButtonsMessageButtonsMessageHeaderType" = betterproto.enum_field(10)
    text: str = betterproto.string_field(1, group="header")
    document_message: "DocumentMessage" = betterproto.message_field(2, group="header")
    image_message: "ImageMessage" = betterproto.message_field(3, group="header")
    video_message: "VideoMessage" = betterproto.message_field(4, group="header")
    location_message: "LocationMessage" = betterproto.message_field(5, group="header")


@dataclass
class ButtonsResponseMessage(betterproto.Message):
    selected_button_id: str = betterproto.string_field(1)
    context_info: "ContextInfo" = betterproto.message_field(3)
    type: "ButtonsResponseMessageButtonsResponseMessageType" = betterproto.enum_field(4)
    selected_display_text: str = betterproto.string_field(2, group="response")


@dataclass
class Message(betterproto.Message):
    conversation: str = betterproto.string_field(1)
    sender_key_distribution_message: "SenderKeyDistributionMessage" = (
        betterproto.message_field(2)
    )
    image_message: "ImageMessage" = betterproto.message_field(3)
    contact_message: "ContactMessage" = betterproto.message_field(4)
    location_message: "LocationMessage" = betterproto.message_field(5)
    extended_text_message: "ExtendedTextMessage" = betterproto.message_field(6)
    document_message: "DocumentMessage" = betterproto.message_field(7)
    audio_message: "AudioMessage" = betterproto.message_field(8)
    video_message: "VideoMessage" = betterproto.message_field(9)
    call: "Call" = betterproto.message_field(10)
    chat: "Chat" = betterproto.message_field(11)
    protocol_message: "ProtocolMessage" = betterproto.message_field(12)
    contacts_array_message: "ContactsArrayMessage" = betterproto.message_field(13)
    highly_structured_message: "HighlyStructuredMessage" = betterproto.message_field(14)
    fast_ratchet_key_sender_key_distribution_message: "SenderKeyDistributionMessage" = (
        betterproto.message_field(15)
    )
    send_payment_message: "SendPaymentMessage" = betterproto.message_field(16)
    live_location_message: "LiveLocationMessage" = betterproto.message_field(18)
    request_payment_message: "RequestPaymentMessage" = betterproto.message_field(22)
    decline_payment_request_message: "DeclinePaymentRequestMessage" = (
        betterproto.message_field(23)
    )
    cancel_payment_request_message: "CancelPaymentRequestMessage" = (
        betterproto.message_field(24)
    )
    template_message: "TemplateMessage" = betterproto.message_field(25)
    sticker_message: "StickerMessage" = betterproto.message_field(26)
    group_invite_message: "GroupInviteMessage" = betterproto.message_field(28)
    template_button_reply_message: "TemplateButtonReplyMessage" = (
        betterproto.message_field(29)
    )
    product_message: "ProductMessage" = betterproto.message_field(30)
    device_sent_message: "DeviceSentMessage" = betterproto.message_field(31)
    message_context_info: "MessageContextInfo" = betterproto.message_field(35)
    list_message: "ListMessage" = betterproto.message_field(36)
    view_once_message: "FutureProofMessage" = betterproto.message_field(37)
    order_message: "OrderMessage" = betterproto.message_field(38)
    list_response_message: "ListResponseMessage" = betterproto.message_field(39)
    ephemeral_message: "FutureProofMessage" = betterproto.message_field(40)
    invoice_message: "InvoiceMessage" = betterproto.message_field(41)
    buttons_message: "ButtonsMessage" = betterproto.message_field(42)
    buttons_response_message: "ButtonsResponseMessage" = betterproto.message_field(43)
    payment_invite_message: "PaymentInviteMessage" = betterproto.message_field(44)


@dataclass
class CompanionProps(betterproto.Message):
    os: str = betterproto.string_field(1)
    version: "AppVersion" = betterproto.message_field(2)
    platform_type: "CompanionPropsCompanionPropsPlatformType" = betterproto.enum_field(
        3
    )
    require_full_sync: bool = betterproto.bool_field(4)


@dataclass
class ADVSignedDeviceIdentityHMAC(betterproto.Message):
    details: bytes = betterproto.bytes_field(1)
    hmac: bytes = betterproto.bytes_field(2)


@dataclass
class ADVSignedDeviceIdentity(betterproto.Message):
    details: bytes = betterproto.bytes_field(1)
    account_signature_key: bytes = betterproto.bytes_field(2)
    account_signature: bytes = betterproto.bytes_field(3)
    device_signature: bytes = betterproto.bytes_field(4)


@dataclass
class ADVDeviceIdentity(betterproto.Message):
    raw_id: int = betterproto.uint32_field(1)
    timestamp: int = betterproto.uint64_field(2)
    key_index: int = betterproto.uint32_field(3)


@dataclass
class ADVSignedKeyIndexList(betterproto.Message):
    details: bytes = betterproto.bytes_field(1)
    account_signature: bytes = betterproto.bytes_field(2)


@dataclass
class ADVKeyIndexList(betterproto.Message):
    raw_id: int = betterproto.uint32_field(1)
    timestamp: int = betterproto.uint64_field(2)
    current_index: int = betterproto.uint32_field(3)
    valid_indexes: List[int] = betterproto.uint32_field(4)


@dataclass
class MessageKey(betterproto.Message):
    remote_jid: str = betterproto.string_field(1)
    from_me: bool = betterproto.bool_field(2)
    id: str = betterproto.string_field(3)
    participant: str = betterproto.string_field(4)


@dataclass
class PhotoChange(betterproto.Message):
    old_photo: bytes = betterproto.bytes_field(1)
    new_photo: bytes = betterproto.bytes_field(2)
    new_photo_id: int = betterproto.uint32_field(3)


@dataclass
class MediaData(betterproto.Message):
    local_path: str = betterproto.string_field(1)


@dataclass
class WebFeatures(betterproto.Message):
    labels_display: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(1)
    voip_individual_outgoing: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(2)
    groups_v3: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(3)
    groups_v3_create: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(4)
    change_number_v2: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(5)
    query_status_v3_thumbnail: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(6)
    live_locations: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(7)
    query_vname: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(8)
    voip_individual_incoming: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(9)
    quick_replies_query: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(10)
    payments: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(11)
    sticker_pack_query: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(12)
    live_locations_final: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(13)
    labels_edit: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(14)
    media_upload: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(15)
    media_upload_rich_quick_replies: "WebFeaturesWebFeaturesFlag" = (
        betterproto.enum_field(18)
    )
    vname_v2: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(19)
    video_playback_url: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(20)
    status_ranking: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(21)
    voip_individual_video: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(22)
    third_party_stickers: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(23)
    frequently_forwarded_setting: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(
        24
    )
    groups_v4_join_permission: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(25)
    recent_stickers: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(26)
    catalog: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(27)
    starred_stickers: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(28)
    voip_group_call: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(29)
    template_message: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(30)
    template_message_interactivity: "WebFeaturesWebFeaturesFlag" = (
        betterproto.enum_field(31)
    )
    ephemeral_messages: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(32)
    e2_e_notification_sync: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(33)
    recent_stickers_v2: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(34)
    recent_stickers_v3: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(36)
    user_notice: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(37)
    support: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(39)
    group_uii_cleanup: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(40)
    group_dogfooding_internal_only: "WebFeaturesWebFeaturesFlag" = (
        betterproto.enum_field(41)
    )
    settings_sync: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(42)
    archive_v2: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(43)
    ephemeral_allow_group_members: "WebFeaturesWebFeaturesFlag" = (
        betterproto.enum_field(44)
    )
    ephemeral24_h_duration: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(45)
    md_force_upgrade: "WebFeaturesWebFeaturesFlag" = betterproto.enum_field(46)


@dataclass
class NotificationMessageInfo(betterproto.Message):
    key: "MessageKey" = betterproto.message_field(1)
    message: "Message" = betterproto.message_field(2)
    message_timestamp: int = betterproto.uint64_field(3)
    participant: str = betterproto.string_field(4)


@dataclass
class WebNotificationsInfo(betterproto.Message):
    timestamp: int = betterproto.uint64_field(2)
    unread_chats: int = betterproto.uint32_field(3)
    notify_message_count: int = betterproto.uint32_field(4)
    notify_messages: List["WebMessageInfo"] = betterproto.message_field(5)


@dataclass
class PaymentInfo(betterproto.Message):
    currency_deprecated: "PaymentInfoPaymentInfoCurrency" = betterproto.enum_field(1)
    amount1000: int = betterproto.uint64_field(2)
    receiver_jid: str = betterproto.string_field(3)
    status: "PaymentInfoPaymentInfoStatus" = betterproto.enum_field(4)
    transaction_timestamp: int = betterproto.uint64_field(5)
    request_message_key: "MessageKey" = betterproto.message_field(6)
    expiry_timestamp: int = betterproto.uint64_field(7)
    futureproofed: bool = betterproto.bool_field(8)
    currency: str = betterproto.string_field(9)
    txn_status: "PaymentInfoPaymentInfoTxnStatus" = betterproto.enum_field(10)
    use_novi_fiat_format: bool = betterproto.bool_field(11)
    primary_amount: "Money" = betterproto.message_field(12)
    exchange_amount: "Money" = betterproto.message_field(13)


@dataclass
class WebMessageInfo(betterproto.Message):
    key: "MessageKey" = betterproto.message_field(1)
    message: "Message" = betterproto.message_field(2)
    message_timestamp: int = betterproto.uint64_field(3)
    status: "WebMessageInfoWebMessageInfoStatus" = betterproto.enum_field(4)
    participant: str = betterproto.string_field(5)
    message_c2_s_timestamp: int = betterproto.uint64_field(6)
    ignore: bool = betterproto.bool_field(16)
    starred: bool = betterproto.bool_field(17)
    broadcast: bool = betterproto.bool_field(18)
    push_name: str = betterproto.string_field(19)
    media_ciphertext_sha256: bytes = betterproto.bytes_field(20)
    multicast: bool = betterproto.bool_field(21)
    url_text: bool = betterproto.bool_field(22)
    url_number: bool = betterproto.bool_field(23)
    message_stub_type: "WebMessageInfoWebMessageInfoStubType" = betterproto.enum_field(
        24
    )
    clear_media: bool = betterproto.bool_field(25)
    message_stub_parameters: List[str] = betterproto.string_field(26)
    duration: int = betterproto.uint32_field(27)
    labels: List[str] = betterproto.string_field(28)
    payment_info: "PaymentInfo" = betterproto.message_field(29)
    final_live_location: "LiveLocationMessage" = betterproto.message_field(30)
    quoted_payment_info: "PaymentInfo" = betterproto.message_field(31)
    ephemeral_start_timestamp: int = betterproto.uint64_field(32)
    ephemeral_duration: int = betterproto.uint32_field(33)
    ephemeral_off_to_on: bool = betterproto.bool_field(34)
    ephemeral_out_of_sync: bool = betterproto.bool_field(35)
    biz_privacy_status: "WebMessageInfoWebMessageInfoBizPrivacyStatus" = (
        betterproto.enum_field(36)
    )
    verified_biz_name: str = betterproto.string_field(37)
    media_data: "MediaData" = betterproto.message_field(38)
    photo_change: "PhotoChange" = betterproto.message_field(39)
